
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qasim Inayat
 */
public class StudentPerformance extends javax.swing.JFrame {

    /**
     * Creates new form StudentPerformance
     */
    public StudentPerformance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AutoButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jITCPSessionalTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jITCPMidTF = new javax.swing.JTextField();
        jITCPFinalTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ResultITCPL = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCPSessionalTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jCPMidlTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCPFinallTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ResultLCPL = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jOOPSessionallTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jOOPMidlTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jOOPFinallTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ResultOOPL = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jVPSessionallTF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jVPMidlTF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jVPFinallTF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        ResultVPL = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jFPSessionallTF = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jFPMidlTF = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jFPFinallTF = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        ResultFPL = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        StRemarksCB = new javax.swing.JComboBox();
        StRemarksCB2 = new javax.swing.JComboBox();
        StRemarksCB3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jCommentTF = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        jStudentNameCB = new javax.swing.JComboBox();
        jStudentIDCB = new javax.swing.JComboBox();
        TotalResultL = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Course Title");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Greenland Schooling System | Student's Performance");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(173, 162, 53));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nexa Bold", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student's Performance");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Student Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Student ID");

        AutoButton.setText("Click to Set Auto");
        AutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Student's Information");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Student's Marks");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Sessional");

        jITCPSessionalTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jITCPSessionalTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jITCPSessionalTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jITCPSessionalTFKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("ITCP");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Mid");

        jITCPMidTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jITCPMidTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jITCPMidTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jITCPMidTFKeyTyped(evt);
            }
        });

        jITCPFinalTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jITCPFinalTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jITCPFinalTFKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Final");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Total");

        ResultITCPL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("/  100");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("CP");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Sessional");

        jCPSessionalTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCPSessionalTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCPSessionalTFKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Mid");

        jCPMidlTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCPMidlTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCPMidlTFKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Final");

        jCPFinallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCPFinallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCPFinallTFKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Total");

        ResultLCPL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("/  100");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("OOP");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Sessional");

        jOOPSessionallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jOOPSessionallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jOOPSessionallTFKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Mid");

        jOOPMidlTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jOOPMidlTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jOOPMidlTFKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Final");

        jOOPFinallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jOOPFinallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jOOPFinallTFKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Total");

        ResultOOPL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("/  100");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("VP");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Sessional");

        jVPSessionallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jVPSessionallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jVPSessionallTFKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Mid");

        jVPMidlTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jVPMidlTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jVPMidlTFKeyTyped(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Final");

        jVPFinallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jVPFinallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jVPFinallTFKeyTyped(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Total");

        ResultVPL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("/  100");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("FP");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Sessional");

        jFPSessionallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jFPSessionallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFPSessionallTFKeyTyped(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Mid");

        jFPMidlTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jFPMidlTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFPMidlTFKeyTyped(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Final");

        jFPFinallTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jFPFinallTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFPFinallTFKeyTyped(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Total");

        ResultFPL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("/ 100");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel39.setText("Student's Remarking");

        StRemarksCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Extremely Good", "Good", "Extremely Bad", "Bad" }));

        StRemarksCB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Extremely Good", "Good", "Extremely Bad", "Bad" }));

        StRemarksCB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Full", "Average", "None" }));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 162, 53), 5));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student", "ID", "Result", "Performance", "Performance", "Performance", "Comment"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("Comment");

        jCommentTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCommentTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCommentTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCommentTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCommentTFKeyTyped(evt);
            }
        });

        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        Message.setForeground(new java.awt.Color(255, 51, 51));

        jStudentNameCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Qasim Inayat", "Uzair Khan", "Zubair Khan", "Omair Khan" }));

        jStudentIDCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "4115", "4116", "4117", "4118", "" }));

        TotalResultL.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel42.setText("Total");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Student Seriousness");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setText("Student Participation");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setText("Student Activness");

        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel21))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(jOOPSessionallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(jOOPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jOOPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCPSessionalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(jVPSessionallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(jVPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18)
                                        .addComponent(jVPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFPSessionallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel35)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel36)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(156, 156, 156))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(4, 4, 4)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(ResultLCPL, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                                    .addComponent(ResultITCPL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel15)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ResultOOPL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel26)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jITCPSessionalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jITCPMidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jITCPFinalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel43)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(285, 285, 285)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(StRemarksCB, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StRemarksCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StRemarksCB3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 524, Short.MAX_VALUE)
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResultVPL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel27))
                                        .addGap(502, 502, 502)
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResultFPL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TotalResultL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(67, 67, 67)))
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(jCommentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(64, 64, 64)
                                .addComponent(jStudentNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(jStudentIDCB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(602, 602, 602)
                                .addComponent(AutoButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(UpdateButton)
                                .addGap(57, 57, 57)
                                .addComponent(DeleteButton)
                                .addGap(411, 411, 411)
                                .addComponent(ClearButton))
                            .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStudentNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStudentIDCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AutoButton)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ResultITCPL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jITCPSessionalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jITCPMidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jITCPFinalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCPSessionalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOOPSessionallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOOPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOOPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ResultLCPL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ResultOOPL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultVPL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jVPSessionallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jVPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jVPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jFPSessionallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jFPMidlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jFPFinallTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(ResultFPL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalResultL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(StRemarksCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StRemarksCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StRemarksCB3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(jCommentTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1712, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1298, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoButtonActionPerformed
       AuttonButton();
    }//GEN-LAST:event_AutoButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        AddButton();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        UpdateButton();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       //MouseClick();
    }//GEN-LAST:event_jTable1MouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
       DeleteButton();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
       ClearButton();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jCommentTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCommentTFKeyPressed
   /*  if(jCommentTF.getText().equals("0")|| jCommentTF.getText().equals("1") || jCommentTF.getText().equals("2") || jCommentTF.getText().equals("3") || jCommentTF.getText().equals("4") || jCommentTF.getText().equals("5") || jCommentTF.getText().equals("6") || jCommentTF.getText().equals("5") || jCommentTF.getText().equals("6") || jCommentTF.getText().equals("7") || jCommentTF.getText().equals("8") || jCommentTF.getText().equals("9") )
     {
         JOptionPane.showMessageDialog(this, "Wrong Input!");
     }
        
      /*try
      {
          Double.parseDouble(jCommentTF.getText());
      }
      catch(NumberFormatException x)
      {
          JOptionPane.showMessageDialog(rootPane, "Wrong Input!");
                  
                  
      }*/
    }//GEN-LAST:event_jCommentTFKeyPressed

    private void jCommentTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCommentTFKeyTyped
     char c = evt.getKeyChar();
       if(Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jCommentTFKeyTyped

    private void jCommentTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCommentTFKeyReleased
    /*   if(jCommentTF.getText().equals("0")|| jCommentTF.getText().equals("1") || jCommentTF.getText().equals("2") || jCommentTF.getText().equals("3") || jCommentTF.getText().equals("4") || jCommentTF.getText().equals("5") || jCommentTF.getText().equals("6") || jCommentTF.getText().equals("5") || jCommentTF.getText().equals("6") || jCommentTF.getText().equals("7") || jCommentTF.getText().equals("8") || jCommentTF.getText().equals("9") )
     {
         JOptionPane.showMessageDialog(this, "Wrong Input!");
     }*/
    }//GEN-LAST:event_jCommentTFKeyReleased

    private void jITCPSessionalTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jITCPSessionalTFKeyReleased
     
    }//GEN-LAST:event_jITCPSessionalTFKeyReleased

    private void jITCPMidTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jITCPMidTFKeyReleased
        
    }//GEN-LAST:event_jITCPMidTFKeyReleased

    private void jITCPSessionalTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jITCPSessionalTFKeyTyped
       char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jITCPSessionalTFKeyTyped

    private void jITCPMidTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jITCPMidTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jITCPMidTFKeyTyped

    private void jITCPFinalTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jITCPFinalTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           //getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_jITCPFinalTFKeyTyped

    private void jCPSessionalTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPSessionalTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jCPSessionalTFKeyTyped

    private void jCPMidlTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPMidlTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jCPMidlTFKeyTyped

    private void jCPFinallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPFinallTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jCPFinallTFKeyTyped

    private void jOOPSessionallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOOPSessionallTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jOOPSessionallTFKeyTyped

    private void jOOPMidlTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOOPMidlTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jOOPMidlTFKeyTyped

    private void jOOPFinallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOOPFinallTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jOOPFinallTFKeyTyped

    private void jVPSessionallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVPSessionallTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jVPSessionallTFKeyTyped

    private void jVPMidlTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVPMidlTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jVPMidlTFKeyTyped

    private void jVPFinallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVPFinallTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jVPFinallTFKeyTyped

    private void jFPSessionallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFPSessionallTFKeyTyped
        char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jFPSessionallTFKeyTyped

    private void jFPMidlTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFPMidlTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c))
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jFPMidlTFKeyTyped

    private void jFPFinallTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFPFinallTFKeyTyped
         char c = evt.getKeyChar();
       if(!Character.isDigit(c) )
       {
           
           evt.consume();
       }
    }//GEN-LAST:event_jFPFinallTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPerformance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AutoButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel ResultFPL;
    private javax.swing.JLabel ResultITCPL;
    private javax.swing.JLabel ResultLCPL;
    private javax.swing.JLabel ResultOOPL;
    private javax.swing.JLabel ResultVPL;
    private javax.swing.JComboBox StRemarksCB;
    private javax.swing.JComboBox StRemarksCB2;
    private javax.swing.JComboBox StRemarksCB3;
    private javax.swing.JLabel TotalResultL;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField jCPFinallTF;
    private javax.swing.JTextField jCPMidlTF;
    private javax.swing.JTextField jCPSessionalTF;
    private javax.swing.JTextField jCommentTF;
    private javax.swing.JTextField jFPFinallTF;
    private javax.swing.JTextField jFPMidlTF;
    private javax.swing.JTextField jFPSessionallTF;
    private javax.swing.JTextField jITCPFinalTF;
    private javax.swing.JTextField jITCPMidTF;
    private javax.swing.JTextField jITCPSessionalTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jOOPFinallTF;
    private javax.swing.JTextField jOOPMidlTF;
    private javax.swing.JTextField jOOPSessionallTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jStudentIDCB;
    private javax.swing.JComboBox jStudentNameCB;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jVPFinallTF;
    private javax.swing.JTextField jVPMidlTF;
    private javax.swing.JTextField jVPSessionallTF;
    // End of variables declaration//GEN-END:variables

    BussinessLogic c = new BussinessLogic();
    String Student_Name,Student_ID,Comment;
    int ITCPSessional, ITCPMid, ITCPFinal, CPSessional, CPMid, CPFinal, OOPSessional, OOPPMid, OOPFinal, VPSessional, VPMid, VPFinal,FPSessional, FPMid, FPFinal, ResultITCP;
    public void AuttonButton()
    {
        Student_Name = jStudentNameCB.getSelectedItem().toString();
        Student_ID = jStudentIDCB.getSelectedItem().toString();
        
        if(jStudentNameCB.getSelectedItem().toString().equals("Qasim Inayat"))
        {
            jStudentIDCB.setSelectedItem("4115");
        }
        
        else if(jStudentNameCB.getSelectedItem().toString().equals("Uzair Khan"))
        {
            jStudentIDCB.setSelectedItem("4116");
        }
        
        else if(jStudentNameCB.getSelectedItem().toString().equals("Zubair Khan"))
        {
            jStudentIDCB.setSelectedItem("4117");
        }
        
        else if(jStudentNameCB.getSelectedItem().toString().equals("Omair Khan"))
        {
            jStudentIDCB.setSelectedItem("4118");
        }
        
        else
        {
            //Do Nothing
        
        }
        
        
       /* if(jStudentIDCB.getSelectedItem().toString().equals("4115"))
        {
            jStudentNameCB.setSelectedItem("Qasim Inayat");
        }
        else if(jStudentIDCB.getSelectedItem().toString().equals("4116"))
        {
            jStudentNameCB.setSelectedItem("Uzair Khan");
        }
        else if(jStudentIDCB.getSelectedItem().toString().equals("4117"))
        {
            jStudentNameCB.setSelectedItem("Zubair Khan");
        }
        else if(jStudentIDCB.getSelectedItem().toString().equals("4118"))
        {
            jStudentNameCB.setSelectedItem("Omair Khan");
        }
        
        else
        {
            //Do Nothing
        }*/
        
        
       
        
    }
    
    public void AddButton()
    {
        
      try
      {
        Student_Name=jStudentNameCB.getSelectedItem().toString();
        Student_ID = jStudentIDCB.getSelectedItem().toString();
        ITCPSessional=Integer.parseInt(jITCPSessionalTF.getText());
        ITCPMid=Integer.parseInt(jITCPMidTF.getText());
        ITCPFinal=Integer.parseInt(jITCPFinalTF.getText());
        CPSessional=Integer.parseInt(jCPSessionalTF.getText());
        CPMid=Integer.parseInt(jCPMidlTF.getText());
        CPFinal=Integer.parseInt(jCPFinallTF.getText());
        OOPSessional=Integer.parseInt(jOOPSessionallTF.getText());
        OOPPMid=Integer.parseInt(jOOPMidlTF.getText());
        OOPFinal=Integer.parseInt(jOOPFinallTF.getText());
        VPSessional=Integer.parseInt(jVPSessionallTF.getText());
        VPMid=Integer.parseInt(jVPMidlTF.getText());
        VPFinal=Integer.parseInt(jVPFinallTF.getText());
        FPSessional=Integer.parseInt(jFPSessionallTF.getText());
        FPMid=Integer.parseInt(jFPMidlTF.getText());
        FPFinal=Integer.parseInt(jFPFinallTF.getText());
      }
      
      catch(NumberFormatException x)
       {
          JOptionPane.showMessageDialog(null, "Please Enter Full Form");
       }
        Comment = jCommentTF.getText();
        
        
        
        ResultITCPL.setText(c.ITCP(ITCPSessional, ITCPMid, ITCPFinal)+"");
        ResultLCPL.setText(c.CP(CPSessional, CPMid, CPFinal)+"");
        ResultOOPL.setText(c.OOP(OOPSessional, OOPPMid, OOPFinal)+"");
        ResultVPL.setText(c.VP(VPSessional, VPMid, VPFinal)+"");
        ResultFPL.setText(c.FP(FPSessional, FPMid, FPFinal)+"");

        TotalResultL.setText(c.ITCP(ITCPSessional, ITCPMid, ITCPFinal)+c.CP(CPSessional, CPMid, CPFinal)+c.OOP(OOPSessional, OOPPMid, OOPFinal)+c.VP(VPSessional, VPMid, VPFinal)+c.FP(FPSessional, FPMid, FPFinal)+"");
        
        Message.setText("");
        if(!jStudentNameCB.getSelectedItem().equals(""))
        {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{ jStudentNameCB.getSelectedItem().toString(), jStudentIDCB.getSelectedItem().toString(), TotalResultL.getText(),StRemarksCB.getSelectedItem().toString(),StRemarksCB2.getSelectedItem().toString(),StRemarksCB3.getSelectedItem().toString(), jCommentTF.getText()});
        }
        else
        {
           // Message.setText("No Selection! Please make a Selection First");
        }
     
    }
    
    public void UpdateButton()
    {
        Message.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1)
        {
            if(jTable1.getRowCount()==0)
            {
                Message.setText("There is no Field to Upadate");
            }
            else
            {
                Message.setText("You must Select the Particular Field that you want to Update");
            }
        }
        else
        {
            model.setValueAt(jStudentNameCB.getSelectedItem().toString(),jTable1.getSelectedRow(), 0);
            model.setValueAt(jStudentIDCB.getSelectedItem().toString(),jTable1.getSelectedRow(), 1);
            model.setValueAt(TotalResultL.getText(),jTable1.getSelectedRow(), 2);
            model.setValueAt(StRemarksCB.getSelectedItem().toString(),jTable1.getSelectedRow(), 3);
            model.setValueAt(StRemarksCB2.getSelectedItem().toString(),jTable1.getSelectedRow(), 4);
            model.setValueAt(StRemarksCB3.getSelectedItem().toString(),jTable1.getSelectedRow(), 5);
            model.setValueAt(jCommentTF.getText(),jTable1.getSelectedRow(), 6);
        }
        
    }
    
    /*public void MouseClick()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jStudentNameCB.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jStudentIDCB.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
        //TotalResultL.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        StRemarksCB.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
        StRemarksCB2.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
        StRemarksCB3.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
        //jCommentTF.setText(model.getValueAt(jTable1.getSelectedRow(), 5).toString());
        
    }*/
    
    public void DeleteButton()
    {
        
        Message.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1)
        {
            if(jTable1.getRowCount()==0)
            {
                Message.setText("There is no Field to Delete");
            }
            else
            {
                Message.setText("You must Select the Particular Field that you want to Delete");
            }
        }    
        else
        {
            model.removeRow(jTable1.getSelectedRow());
                    
        }
    }
    
    public void ClearButton()
    {
        if(StRemarksCB3.getSelectedItem().equals("Full") || StRemarksCB3.getSelectedItem().equals("Average") || StRemarksCB3.getSelectedItem().equals("None"))
        {
            jStudentNameCB.setSelectedItem("");
            jStudentIDCB.setSelectedItem("");
            jITCPSessionalTF.setText("");
            jITCPMidTF.setText("");
            jITCPFinalTF.setText("");
            jCPSessionalTF.setText("");
            jCPMidlTF.setText("");
            jCPFinallTF.setText("");
            jOOPSessionallTF.setText("");
            jOOPMidlTF.setText("");
            jOOPFinallTF.setText("");
            jVPSessionallTF.setText("");
            jVPMidlTF.setText("");
            jVPFinallTF.setText("");
            jFPSessionallTF.setText("");
            jFPMidlTF.setText("");
            jFPFinallTF.setText("");
            TotalResultL.setText("");
            StRemarksCB.setSelectedItem("");
            StRemarksCB2.setSelectedItem("");
            StRemarksCB3.setSelectedItem("");
            jCommentTF.setText("");
            Message.setText("");
            
            
        }
    }
    
    

}
